services:
  rust:
    build:
      context: .
      dockerfile: Dockerfile
    image: rust-dev:latest
    container_name: rust_dev
    user: "${UID}:${GID}"
    working_dir: /workspace
    restart: unless-stopped
    tty: true
    stdin_open: true
    command: sleep infinity
    volumes:
      - personal_ws:/workspace
      - ~/personal_ws:/personal_ws

volumes:
  personal_ws:
    external: true
